markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : Kevoree Project
production_url : http://blog.kevoree.org
description: "Kevoree Project : Blog"
disqus_shortname: kevoree
analytics: 
gauges: 
paginate: 5
author :
  name : Francois Fouquet
  github : dukeboard
  twitter : kevoree
 
